# Generated by Django 6.0.5 on 2026-05-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Língua', 'verbose_name_plural': 'Línguas'},
        ),
    ]
